languageCode = "en"
languageName = "English"
weight = 1
title = "Steven Lawrence"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "January 2 2006"

[author]
name = "Steven Lawrence"
image = "img/StevenLawrence.jpg"
headline = "Voxel Enthusiast"