[[main]]
none = "none"

[[main]]
name = "Employment"
pageRef = "Employment"
weight = 1

[[main]]
name = "Projects"
pageRef = "Projects"
weight = 2

[[main]]
name = "VANG"
parent = "Projects"
pageRef = "VANG"
weight = 2

[[main]]
name = "Unity"
parent = "Projects"
pageRef = "Unity"
weight = 3

[[main]]
name = "GameMaker"
parent = "Projects"
pageRef = "GameMaker"
weight = 4

[[main]]
name = "Animation"
parent = "Projects"
pageRef = "Animation"
weight = 5

[[main]]
name = "Unreal"
parent = "Projects"
pageRef = "Unreal"
weight = 6

[[main]]
name = "Other"
parent = "Projects"
pageRef = "Other"
weight = 7

[[footer]]
none = "none"
